openapi: 3.0.1
info:
  title: AEGEATEST
  description: API Definition of AEGEATEST
  version: 1.0.0
servers:
- url: http://localhost:8290/AEGEATEST
paths:
  /:
    get:
      responses:
        default:
          description: Default response
