openapi: 3.0.1
info:
  title: AEGEA
  description: API Definition of AEGEA
  version: 1.0.0
servers:
- url: http://localhost:8290/AEGEA
paths:
  /:
    get:
      responses:
        default:
          description: Default response
