openapi: 3.0.1
info:
  title: OAuthTokenAPI
  description: API Definition of OAuthTokenAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/getOAuthToken
paths:
  /:
    get:
      responses:
        default:
          description: Default response
