openapi: 3.0.1
info:
  title: ProcessDataAPITest
  description: API Definition of ProcessDataAPITest
  version: 1.0.0
servers:
- url: http://localhost:8290/ProcessDataAPI
paths:
  /:
    get:
      responses:
        default:
          description: Default response
