openapi: 3.0.1
info:
  title: ProcessDataAPIDemo
  description: API Definition of ProcessDataAPIDemo
  version: 1.0.0
servers:
- url: http://localhost:8290/ProcessData
paths:
  /:
    get:
      responses:
        default:
          description: Default response
