openapi: 3.0.1
info:
  title: ProcessDataAPIBeta
  description: API Definition of ProcessDataAPIBeta
  version: 1.0.0
servers:
- url: http://localhost:8290/ProcessDataAPIBeta
paths:
  /:
    get:
      responses:
        default:
          description: Default response
