openapi: 3.0.1
info:
  title: ProcessDataAPI
  description: API Definition of ProcessDataAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/processData
paths:
  /:
    get:
      responses:
        default:
          description: Default response
