openapi: 3.0.1
info:
  title: ProcessDataAPISample
  description: API Definition of ProcessDataAPISample
  version: 1.0.0
servers:
- url: http://localhost:8290/ProcessDataAPISample
paths:
  /:
    get:
      responses:
        default:
          description: Default response
